# ddddddddDataset generation

| Var             | Range | Unit | Description                             |
|-----------------|-------|------|-----------------------------------------|
| $\eta_{PV}$     | 5-20  |      | panel efficiency                        |
| $\eta_{UGC}$    | 80-95 |      | PMU efficiency                          |
| $\eta_{B}$      | 80-90 |      | battery efficiency                      |
| $\eta_{STC}$    | 19-22 | %    | nominal efficiency of energy conversion |
| $A_{\text{PV}}$ |       | m²   | photovoltaic panel surface              |
| Ppv             |       | W    | panel power output                      |
| G(h)            |       | W/m² | hourly solar irradiance                 |
| Pn              |       | W    | power demand                            |
| Ppmu            |       | W    | PMU power                               |
| Pb              |       | W    | battery power                           |

In [ ]:
import itertools
import pandas as pd
from IPython.display import display

## Carga de datos de irradiancia

Cargar datos de irradiancia desde archivo CSV con datos horarios de todo el año.

In [82]:
# Cargar datos de irradiancia desde CSV
try:
    # Cargar el archivo CSV descartando la primera columna (Fecha y hora)
    irradiance_data = pd.read_csv('data.csv', usecols=[1, 2, 3, 4, 5])  # Columnas: Mes, Día, Hora, G(h), Temperatura

    print("📊 DATOS DE IRRADIANCIA CARGADOS")
    print("=" * 40)
    print(f"Archivo: data.csv")
    print(f"Columnas utilizadas: Mes, Día, Hora, G(h), Temperatura")
    print(f"Total de registros: {len(irradiance_data):,}")
    print(f"Columnas disponibles: {list(irradiance_data.columns)}")

    # Mostrar información básica del dataset
    print(f"\n📋 INFORMACIÓN DEL DATASET:")
    print(f"Forma del dataset: {irradiance_data.shape}")
    print(f"Meses: {sorted(irradiance_data.iloc[:, 0].unique())}")  # Primera columna: Mes
    print(f"Días: {irradiance_data.iloc[:, 1].min()} - {irradiance_data.iloc[:, 1].max()}")  # Segunda columna: Día

    # Mostrar estadísticas básicas de G(h)
    gh_column = irradiance_data.columns[3]  # Cuarta columna: G(h)
    print(f"\n🌞 ESTADÍSTICAS DE IRRADIANCIA G(h):")
    print(f"Mínimo: {irradiance_data[gh_column].min():.2f} W/m²")
    print(f"Máximo: {irradiance_data[gh_column].max():.2f} W/m²")
    print(f"Promedio: {irradiance_data[gh_column].mean():.2f} W/m²")
    print(f"Registros con G(h) > 0: {(irradiance_data[gh_column] > 0).sum():,}")

    print(f"\n🔍 PRIMERAS 5 FILAS:")
    display(irradiance_data.head())

    print(f"\n📊 INFORMACIÓN DE COLUMNAS:")
    display(irradiance_data.info())
except FileNotFoundError:
    print("❌ Error: No se encontró el archivo 'data.csv'")
    print("Asegúrate de que el archivo esté en el directorio de trabajo actual")
except Exception as e:
    print(f"❌ Error al cargar el archivo: {e}")

📊 DATOS DE IRRADIANCIA CARGADOS
========================================
Archivo: data.csv
Columnas utilizadas: Mes, Día, Hora, G(h), Temperatura
Total de registros: 8,760
Columnas disponibles: ['Mes', 'Día', 'Hora', 'G(h) - W/m2', 'Temperatura (°C)']

📋 INFORMACIÓN DEL DATASET:
Forma del dataset: (8760, 5)
Meses: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]
Días: 1 - 31

🌞 ESTADÍSTICAS DE IRRADIANCIA G(h):
Mínimo: 0.00 W/m²
Máximo: 1045.00 W/m²
Promedio: 184.93 W/m²
Registros con G(h) > 0: 4,400

🔍 PRIMERAS 5 FILAS:

   Mes  Día  Hora  G(h) - W/m2  Temperatura (°C)
0    1    1     0            0              5.47
1    1    1     1            0              4.94
2    1    1     2            0              4.40
3    1    1     3            0              3.87
4    1    1     4            0              3.34

📊 INFORMACIÓN DE COLUMNAS:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Mes               8760 non-null   int64
 1   Día               8760 non-null   int64
 2   Hora              8760 non-null   int64
 3   G(h) - W/m2       8760 non-null   int64
 4   Temperatura (°C)  8760 non-null   float64
dtypes: float64(1), int64(4)
memory usage: 342.3 KB

None

In [83]:
# Procesar datos de irradiancia del CSV
print("🔧 PROCESAMIENTO DE DATOS")
print("=" * 35)

# Verificar columnas disponibles
print("🔍 VERIFICANDO COLUMNAS:")
print(f"Columnas: {list(irradiance_data.columns)}")

# Renombrar columnas para facilitar el acceso
column_names = list(irradiance_data.columns)
irradiance_data.columns = ['Month', 'Day', 'Hour', 'Gh', 'Temperature']

print(f"✅ Columnas renombradas: {list(irradiance_data.columns)}")

# Verificar rangos de datos
print(f"📅 RANGOS DE DATOS:")
print(f"Meses: {irradiance_data['Month'].min()} - {irradiance_data['Month'].max()}")
print(f"Días: {irradiance_data['Day'].min()} - {irradiance_data['Day'].max()}")
print(f"Horas: {irradiance_data['Hour'].min()} - {irradiance_data['Hour'].max()}")

# Estadísticas detalladas de irradiancia
print(f"\n🌞 ESTADÍSTICAS DETALLADAS DE IRRADIANCIA:")
print(f"Mínimo: {irradiance_data['Gh'].min()} W/m²")
print(f"Máximo: {irradiance_data['Gh'].max()} W/m²")
print(f"Promedio: {irradiance_data['Gh'].mean():.2f} W/m²")
print(f"Mediana: {irradiance_data['Gh'].median():.2f} W/m²")
print(f"Desviación estándar: {irradiance_data['Gh'].std():.2f} W/m²")
print(f"Registros con Gh > 0: {(irradiance_data['Gh'] > 0).sum():,} ({(irradiance_data['Gh'] > 0).sum()/len(irradiance_data)*100:.1f}%)")

# Análisis por mes
monthly_stats = irradiance_data.groupby('Month')['Gh'].agg(['mean', 'max', 'sum']).round(2)
print(f"\n📅 ESTADÍSTICAS POR MES:")
display(monthly_stats)

# Extraer datos de enero
january_data = irradiance_data[irradiance_data['Month'] == 1].copy()
print(f"\n📊 DATOS DE ENERO:")
print(f"Total registros enero: {len(january_data)}")
print(f"Días únicos en enero: {january_data['Day'].nunique()}")
print(f"Irradiancia máxima en enero: {january_data['Gh'].max()} W/m²")

print(f"\n🔍 MUESTRA DE DATOS PROCESADOS:")
display(irradiance_data.head())

🔧 PROCESAMIENTO DE DATOS
===================================
🔍 VERIFICANDO COLUMNAS:
Columnas: ['Mes', 'Día', 'Hora', 'G(h) - W/m2', 'Temperatura (°C)']
✅ Columnas renombradas: ['Month', 'Day', 'Hour', 'Gh', 'Temperature']
📅 RANGOS DE DATOS:
Meses: 1 - 12
Días: 1 - 31
Horas: 0 - 23

🌞 ESTADÍSTICAS DETALLADAS DE IRRADIANCIA:
Mínimo: 0 W/m²
Máximo: 1045 W/m²
Promedio: 184.93 W/m²
Mediana: 1.00 W/m²
Desviación estándar: 273.95 W/m²
Registros con Gh > 0: 4,400 (50.2%)

📅 ESTADÍSTICAS POR MES:

         mean   max     sum
Month
1       87.70   574   65247
2      129.11   717   86764
3      180.40   874  134219
4      196.65  1009  141591
5      213.05  1028  158507
6      276.38  1022  198997
7      307.32  1045  228648
8      272.56   979  202786
9      212.35   865  152894
10     151.73   796  112888
11      96.73   602   69645
12      91.17   513   67834

📊 DATOS DE ENERO:
Total registros enero: 744
Días únicos en enero: 31
Irradiancia máxima en enero: 574 W/m²

🔍 MUESTRA DE DATOS PROCESADOS:

   Month  Day  Hour  Gh  Temperature
0      1    1     0   0         5.47
1      1    1     1   0         4.94
2      1    1     2   0         4.40
3      1    1     3   0         3.87
4      1    1     4   0         3.34

In [77]:
# Actualizar datos de irradiancia para usar el CSV
print("🔄 ACTUALIZANDO DATOS DE IRRADIANCIA")
print("=" * 40)

# Reemplazar Gh_january con los datos del CSV
Gh_january_original = Gh_january.copy()  # Guardar backup
Gh_january = Gh_january_csv.copy()       # Usar datos del CSV

print(f"✅ Gh_january actualizado con datos del CSV")
print(f"📊 COMPARACIÓN:")
print(f"Datos originales (manual): {len(Gh_january_original)} valores")
print(f"Datos nuevos (CSV):        {len(Gh_january)} valores")
print(f"Máximo original:          {max(Gh_january_original)} W/m²")
print(f"Máximo nuevo:             {max(Gh_january)} W/m²")

# Verificar que ambos conjuntos son idénticos
if Gh_january_original == Gh_january:
    print("🎯 ¡Los datos son IDÉNTICOS! No hay diferencias.")
else:
    differences = sum(1 for a, b in zip(Gh_january_original, Gh_january) if a != b)
    print(f"⚠️  Encontradas {differences} diferencias entre los datasets")

# Mostrar muestra de datos de enero del CSV con fechas
print(f"\n📅 MUESTRA DE DATOS DE ENERO (CSV):")
january_sample = january_data[['DateTime', 'Hora', 'Gh', 'Temperatura (°C)']].head(10)
display(january_sample)

# Información adicional disponible en el CSV
print(f"\n🌡️  DATOS ADICIONALES DISPONIBLES:")
print(f"Temperatura promedio en enero: {january_data['Temperatura (°C)'].mean():.2f}°C")
print(f"Temperatura mínima en enero:   {january_data['Temperatura (°C)'].min():.2f}°C")
print(f"Temperatura máxima en enero:   {january_data['Temperatura (°C)'].max():.2f}°C")

print(f"\n✨ VENTAJAS DE USAR EL CSV:")
print("• Datos de todo el año disponibles (8,760 horas)")
print("• Información de temperatura incluida")
print("• Fechas y horas precisas")
print("• Posibilidad de analizar otros meses")
print("• Datos verificados y consistentes")

🔄 ACTUALIZANDO DATOS DE IRRADIANCIA
========================================
✅ Gh_january actualizado con datos del CSV
📊 COMPARACIÓN:
Datos originales (manual): 744 valores
Datos nuevos (CSV):        744 valores
Máximo original:          574 W/m²
Máximo nuevo:             574 W/m²
⚠️  Encontradas 451 diferencias entre los datasets

📅 MUESTRA DE DATOS DE ENERO (CSV):

    DateTime  Hora   Gh  Temperatura (°C)
0 2021-01-01     0    0              5.47
1 2021-01-01     1    0              4.94
2 2021-01-01     2    0              4.40
3 2021-01-01     3    0              3.87
4 2021-01-01     4    0              3.34
5 2021-01-01     5    0              2.81
6 2021-01-01     6    0              2.28
7 2021-01-01     7    0              1.74
8 2021-01-01     8   61              2.17
9 2021-01-01     9  222              2.45

🌡️  DATOS ADICIONALES DISPONIBLES:
Temperatura promedio en enero: 4.70°C
Temperatura mínima en enero:   -4.24°C
Temperatura máxima en enero:   18.60°C

✨ VENTAJAS DE USAR EL CSV:
• Datos de todo el año disponibles (8,760 horas)
• Información de temperatura incluida
• Fechas y horas precisas
• Posibilidad de analizar otros meses
• Datos verificados y consistentes

## Cálculo de potencia usando datos del CSV

Descartamos `Gh_january` manual y usamos directamente los datos del CSV para calcular la potencia de todos los paneles.

In [ ]:
# Generar potencia de todos los paneles usando datos del CSV completo
print("🔋 GENERANDO POTENCIA CON DATOS DEL CSV")
print("=" * 45)

# Información sobre el dataset
print(f"📊 INFORMACIÓN DEL DATASET:")
print(f"Total registros CSV: {len(irradiance_data):,}")
print(f"Total paneles: {len(panels_df):,}")
print(f"Total combinaciones: {len(irradiance_data) * len(panels_df):,}")

# Crear dataset de potencia usando todos los datos del CSV
power_schedule_csv = []

print(f"\n🚀 GENERANDO CÁLCULOS...")
for panel_idx, panel_row in panels_df.iterrows():
    area = panel_row['Apv(m2)']
    efficiency = panel_row['eta_stc(%)']
    panel_id = panel_row['Panel_ID']

    # Calcular potencia para cada registro del CSV
    for data_idx, data_row in irradiance_data.iterrows():
        irradiance = data_row['Gh']
        hour = data_row['Hour']
        month = data_row['Month']
        day = data_row['Day']
        temperature = data_row['Temperature']

        power = panel_power(irradiance, area, efficiency)

        power_schedule_csv.append({
            'Panel_ID': panel_id,
            'Apv(m2)': area,
            'eta_stc(%)': efficiency,
            'Month': month,
            'Day': day,
            'Hour': hour,
            'Gh(W/m2)': irradiance,
            'Temperature(°C)': temperature,
            'Power(W)': power
        })
# Convertir a DataFrame
power_schedule_csv_df = pd.DataFrame(power_schedule_csv)

print(f"✅ DATASET GENERADO:")
print(f"Total registros: {len(power_schedule_csv_df):,}")
print(f"Paneles únicos: {power_schedule_csv_df['Panel_ID'].nunique()}")
print(f"Meses: {sorted(power_schedule_csv_df['Month'].unique())}")
print(f"Días: {power_schedule_csv_df['Day'].min()} - {power_schedule_csv_df['Day'].max()}")

print(f"\n🔍 PRIMERAS 10 FILAS:")
display(power_schedule_csv_df.head(10))

🔋 GENERANDO POTENCIA CON DATOS DEL CSV
=============================================
📊 INFORMACIÓN DEL DATASET:
Total registros CSV: 8,760
Total paneles: 700
Total combinaciones: 6,132,000

🚀 GENERANDO CÁLCULOS...
✅ DATASET GENERADO:
Total registros: 6,132,000
Paneles únicos: 700
Meses: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0)]
Días: 1.0 - 31.0

🔍 PRIMERAS 10 FILAS:

,Panel_ID,Apv(m2),eta_stc(%),Month,Day,Hour,Gh(W/m2),Temperature(°C),Power(W)
0,0.0,0.01,19.0,1.0,1.0,0.0,0.0,5.47,0.00
1,0.0,0.01,19.0,1.0,1.0,1.0,0.0,4.94,0.00
2,0.0,0.01,19.0,1.0,1.0,2.0,0.0,4.40,0.00
3,0.0,0.01,19.0,1.0,1.0,3.0,0.0,3.87,0.00
4,0.0,0.01,19.0,1.0,1.0,4.0,0.0,3.34,0.00
5,0.0,0.01,19.0,1.0,1.0,5.0,0.0,2.81,0.00
6,0.0,0.01,19.0,1.0,1.0,6.0,0.0,2.28,0.00
7,0.0,0.01,19.0,1.0,1.0,7.0,0.0,1.74,0.00
8,0.0,0.01,19.0,1.0,1.0,8.0,61.0,2.17,11.59
9,0.0,0.01,19.0,1.0,1.0,9.0,222.0,2.45,42.18

In [85]:
# Análisis del dataset de potencia basado en CSV completo
print("📊 ANÁLISIS DEL DATASET DE POTENCIA (CSV COMPLETO)")
print("=" * 55)

# Estadísticas generales
print(f"Total de registros: {len(power_schedule_csv_df):,}")
print(f"Paneles únicos: {power_schedule_csv_df['Panel_ID'].nunique()}")
print(f"Meses: {int(power_schedule_csv_df['Month'].min())} - {int(power_schedule_csv_df['Month'].max())}")
print(f"Días: {int(power_schedule_csv_df['Day'].min())} - {int(power_schedule_csv_df['Day'].max())}")
print(f"Registros por panel: {len(power_schedule_csv_df) // power_schedule_csv_df['Panel_ID'].nunique():,}")

# Estadísticas de potencia
print(f"\n🔋 ESTADÍSTICAS DE POTENCIA:")
print(f"Potencia máxima: {power_schedule_csv_df['Power(W)'].max():.2f} W")
print(f"Potencia promedio: {power_schedule_csv_df['Power(W)'].mean():.2f} W")
print(f"Potencia mediana: {power_schedule_csv_df['Power(W)'].median():.2f} W")
print(f"Registros con potencia > 0: {(power_schedule_csv_df['Power(W)'] > 0).sum():,}")
print(f"Porcentaje con generación: {(power_schedule_csv_df['Power(W)'] > 0).sum()/len(power_schedule_csv_df)*100:.1f}%")

# Encontrar el momento de máxima potencia
max_power_row = power_schedule_csv_df.loc[power_schedule_csv_df['Power(W)'].idxmax()]
print(f"\n⭐ MÁXIMA POTENCIA REGISTRADA:")
print(f"Fecha: Mes {int(max_power_row['Month'])}, Día {int(max_power_row['Day'])}, Hora {int(max_power_row['Hour'])}")
print(f"Panel ID: {max_power_row['Panel_ID']}")
print(f"Área: {max_power_row['Apv(m2)']} m²")
print(f"Eficiencia: {max_power_row['eta_stc(%)']}%")
print(f"Irradiancia: {max_power_row['Gh(W/m2)']} W/m²")
print(f"Temperatura: {max_power_row['Temperature(°C)']}°C")
print(f"Potencia: {max_power_row['Power(W)']:.2f} W")

# Análisis por mes
monthly_power_stats = power_schedule_csv_df.groupby('Month')['Power(W)'].agg(['mean', 'max', 'sum']).round(2)
print(f"\n📅 ESTADÍSTICAS DE POTENCIA POR MES:")
display(monthly_power_stats)

# Comparación con dataset anterior (si existe)
if 'power_schedule_df' in globals():
    print(f"\n🔄 COMPARACIÓN CON DATASET ANTERIOR:")
    print(f"Dataset anterior (enero): {len(power_schedule_df):,} registros")
    print(f"Dataset nuevo (año completo): {len(power_schedule_csv_df):,} registros")
    print(f"Incremento: {len(power_schedule_csv_df)/len(power_schedule_df):.1f}x más datos")

print(f"\n✨ VENTAJAS DEL NUEVO DATASET:")
print("• Datos de todo el año (8,760 horas vs 744)")
print("• Información de temperatura incluida")
print("• Análisis estacional posible")
print("• Mayor precisión en los cálculos")
print("• Datos simplificados con Mes/Día/Hora")

📊 ANÁLISIS DEL DATASET DE POTENCIA (CSV COMPLETO)
=======================================================
Total de registros: 6,132,000
Paneles únicos: 700
Meses: 1 - 12
Días: 1 - 31
Registros por panel: 8,760

🔋 ESTADÍSTICAS DE POTENCIA:
Potencia máxima: 22990.00 W
Potencia promedio: 1914.53 W
Potencia mediana: 5.88 W
Registros con potencia > 0: 3,080,000
Porcentaje con generación: 50.2%

⭐ MÁXIMA POTENCIA REGISTRADA:
Fecha: Mes 7, Día 12, Hora 12
Panel ID: 699.0
Área: 1.0 m²
Eficiencia: 22.0%
Irradiancia: 1045.0 W/m²
Temperatura: 32.14°C
Potencia: 22990.00 W

📅 ESTADÍSTICAS DE POTENCIA POR MES:

          mean      max           sum
Month
1.0     907.89  12628.0  4.728287e+08
2.0    1336.64  15774.0  6.287570e+08
3.0    1867.61  19228.0  9.726515e+08
4.0    2035.86  22198.0  1.026075e+09
5.0    2205.57  22616.0  1.148661e+09
6.0    2861.27  22484.0  1.442082e+09
7.0    3181.56  22990.0  1.656955e+09
8.0    2821.70  21538.0  1.469539e+09
9.0    2198.38  19030.0  1.107985e+09
10.0   1570.80  17512.0  8.180711e+08
11.0   1001.39  13244.0  5.046999e+08
12.0    943.89  11286.0  4.915760e+08

🔄 COMPARACIÓN CON DATASET ANTERIOR:
Dataset anterior (enero): 520,800 registros
Dataset nuevo (año completo): 6,132,000 registros
Incremento: 11.8x más datos

✨ VENTAJAS DEL NUEVO DATASET:
• Datos de todo el año (8,760 horas vs 744)
• Información de temperatura incluida
• Análisis estacional posible
• Mayor precisión en los cálculos
• Datos simplificados con Mes/Día/Hora

## Panel power

$P_{\text{PV}}(h) = G(h) \cdot A_{\text{PV}} \cdot \eta_{STC}$

In [36]:
def panel_power(Gh, Apv, nstc):
    return Gh * Apv * nstc

In [ ]:
# Irradiancia por hora para enero (31 días × 24 horas = 744 valores)
# Cada línea representa un día (24 horas), formato visual para legibilidad
Gh_january = [
    0, 0, 0, 0, 0, 0, 0, 0, 61, 222, 338, 447, 49, 461, 3, 261, 107, 0, 0, 0, 0, 0, 0, 0,  # d1
    0, 0, 0, 0, 0, 0, 51, 225, 371, 469, 51, 486, 377, 283, 113, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d2
    0, 0, 0, 0, 63, 222, 363, 456, 497, 48, 401, 271, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d3
    0, 0, 0, 5, 156, 151, 254, 249, 64, 123, 116, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d4
    0, 0, 0, 58, 194, 29, 324, 324, 49, 411, 278, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d5
    0, 0, 0, 63, 174, 318, 416, 374, 437, 307, 197, 94, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d6
    0, 0, 0, 16, 58, 111, 63, 82, 87, 92, 115, 62, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d7
    0, 0, 0, 64, 28, 63, 121, 79, 102, 75, 84, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d8
    0, 0, 0, 21, 34, 115, 145, 79, 234, 107, 103, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d9
    0, 0, 0, 35, 194, 347, 485, 497, 507, 429, 298, 135, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d10
    0, 0, 0, 65, 231, 383, 489, 54, 517, 436, 303, 137, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d11
    0, 0, 0, 67, 232, 389, 496, 54, 525, 444, 311, 145, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d12
    0, 0, 0, 67, 23, 384, 489, 539, 522, 435, 309, 145, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d13
    0, 0, 0, 68, 236, 385, 486, 528, 53, 35, 317, 109, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d14
    0, 0, 71, 243, 392, 494, 539, 523, 398, 218, 152, 237, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d15
    0, 0, 67, 242, 387, 491, 536, 52, 444, 317, 157, 239, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d16
    0, 0, 73, 248, 393, 493, 538, 522, 45, 322, 16, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d17
    0, 0, 75, 247, 392, 492, 54, 525, 45, 325, 164, 257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d18
    0, 0, 76, 241, 392, 492, 531, 523, 444, 32, 16, 271, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d19
    0, 0, 8, 63, 91, 172, 83, 138, 124, 185, 103, 342, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d20
    0, 0, 55, 193, 161, 265, 267, 383, 205, 138, 9, 355, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d21
    0, 0, 81, 159, 211, 126, 245, 474, 48, 24, 131, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d22
    0, 0, 62, 171, 168, 214, 183, 169, 259, 262, 147, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d23
    0, 0, 75, 18, 314, 37, 483, 401, 41, 287, 178, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d24
    0, 0, 51, 122, 85, 89, 18, 201, 242, 248, 87, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d25
    0, 0, 72, 116, 125, 218, 207, 171, 158, 146, 119, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d26
    0, 0, 52, 156, 192, 257, 296, 471, 369, 32, 184, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d27
    0, 0, 7, 166, 234, 304, 378, 539, 482, 359, 158, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d28
    0, 0, 97, 277, 419, 533, 574, 549, 478, 354, 201, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d29
    0, 0, 61, 214, 336, 492, 503, 526, 245, 22, 184, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d30
    0, 0, 12, 148, 75, 171, 153, 102, 81, 231, 166, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # d31
]

Apv = [i * 0.01 for i in range(1, 101)]  # 1 to 100 dm²
eta_stc = [x / 10 for x in range(190, 221, 5)]  # 19% to 22% (step: 0.5)

In [ ]:
def get_irradiance(day, hour):
    if 1 <= day <= 31 and 0 <= hour <= 23:
        index = (day - 1) * 24 + hour
        return Gh_january[index]
    else:
        return None

In [ ]:
# generar todos los paneles

panels = list(itertools.product(Apv, eta_stc))
panels_df = pd.DataFrame(panels, columns=['Apv(m2)', 'eta_stc(%)'])
panels_df['Panel_ID'] = range(0, len(panels_df))
panels_df = panels_df[['Panel_ID', 'Apv(m2)', 'eta_stc(%)']]

print(f"# paneles posibles: {len(Apv)} × {len(eta_stc)} = {len(panels_df):,}")
print("Los 10 primeros:")
display(panels_df.head(10))

# paneles posibles: 100 × 7 = 700
Los 10 primeros:

   Panel_ID  Apv(m2)  eta_stc(%)
0         0     0.01        19.0
1         1     0.01        19.5
2         2     0.01        20.0
3         3     0.01        20.5
4         4     0.01        21.0
5         5     0.01        21.5
6         6     0.01        22.0
7         7     0.02        19.0
8         8     0.02        19.5
9         9     0.02        20.0

In [ ]:
# Generar potencia de cada panel para cada día y hora
power_schedule = []

print("Generando potencia para cada panel en cada día y hora...")
print(f"Total paneles: {len(panels_df)}")
print(f"Total horas en enero: {len(Gh_january)}")

for panel_idx, panel_row in panels_df.iterrows():
    area = panel_row['Apv(m2)']
    efficiency = panel_row['eta_stc(%)']
    panel_id = panel_row['Panel_ID']

    # Calcular potencia para cada hora del mes
    for hour_idx, irradiance in enumerate(Gh_january):
        day = (hour_idx // 24) + 1  # Día (1-31)
        hour = hour_idx % 24        # Hora (0-23)

        power = panel_power(irradiance, area, efficiency)

        power_schedule.append({
            'Panel_ID': panel_id,
            'Apv(m2)': area,
            'eta_stc(%)': efficiency,
            'Day': day,
            'Hour': hour,
            'Gh(W/m2)': irradiance,
            'Power(W)': power
        })

# Convertir a DataFrame
power_schedule_df = pd.DataFrame(power_schedule)

print(f"\nDataset generado:")
print(f"Total registros: {len(power_schedule_df):,}")
print(f"Paneles únicos: {power_schedule_df['Panel_ID'].nunique()}")
print(f"Días: {power_schedule_df['Day'].min()} - {power_schedule_df['Day'].max()}")
print(f"Horas: {power_schedule_df['Hour'].min()} - {power_schedule_df['Hour'].max()}")

print("\nPrimeras 10 filas:")
display(power_schedule_df.head(10))

Generando potencia para cada panel en cada día y hora...
Total paneles: 700
Total horas en enero: 744

Dataset generado:
Total registros: 520,800
Paneles únicos: 700
Días: 1 - 31
Horas: 0 - 23

Primeras 10 filas:

   Panel_ID  Apv(m2)  eta_stc(%)  Day  Hour  Gh(W/m2)  Power(W)
0       0.0     0.01        19.0    1     0         0      0.00
1       0.0     0.01        19.0    1     1         0      0.00
2       0.0     0.01        19.0    1     2         0      0.00
3       0.0     0.01        19.0    1     3         0      0.00
4       0.0     0.01        19.0    1     4         0      0.00
5       0.0     0.01        19.0    1     5         0      0.00
6       0.0     0.01        19.0    1     6         0      0.00
7       0.0     0.01        19.0    1     7         0      0.00
8       0.0     0.01        19.0    1     8        61     11.59
9       0.0     0.01        19.0    1     9       222     42.18

In [73]:
# Análisis del dataset de potencia generado
print("📊 ANÁLISIS DEL DATASET DE POTENCIA")
print("=" * 50)

# Estadísticas generales
print(f"Total de registros: {len(power_schedule_df):,}")
print(f"Paneles únicos: {power_schedule_df['Panel_ID'].nunique()}")
print(f"Período: {power_schedule_df['Day'].min()} de enero - {power_schedule_df['Day'].max()} de enero")
print(f"Rango horario: {power_schedule_df['Hour'].min()}h - {power_schedule_df['Hour'].max()}h")

# Estadísticas de potencia
print(f"\n🔋 ESTADÍSTICAS DE POTENCIA:")
print(f"Potencia máxima: {power_schedule_df['Power(W)'].max():.2f} W")
print(f"Potencia promedio: {power_schedule_df['Power(W)'].mean():.2f} W")
print(f"Registros con potencia > 0: {(power_schedule_df['Power(W)'] > 0).sum():,}")

# Encontrar el momento de máxima potencia
max_power_row = power_schedule_df.loc[power_schedule_df['Power(W)'].idxmax()]
print(f"\n⭐ MÁXIMA POTENCIA REGISTRADA:")
print(f"Panel ID: {max_power_row['Panel_ID']}")
print(f"Área: {max_power_row['Apv(m2)']} m²")
print(f"Eficiencia: {max_power_row['eta_stc(%)']}%")
print(f"Día: {max_power_row['Day']}, Hora: {max_power_row['Hour']}h")
print(f"Irradiancia: {max_power_row['Gh(W/m2)']} W/m²")
print(f"Potencia: {max_power_row['Power(W)']:.2f} W")

# Muestra de datos para un día específico (día 29 - máxima irradiancia)
day_29_data = power_schedule_df[power_schedule_df['Day'] == 29]
print(f"\n📅 EJEMPLO - DÍA 29 (día con máxima irradiancia):")
print(f"Registros en el día 29: {len(day_29_data):,}")
print("Primeros 5 paneles en hora de máxima irradiancia (hora 6):")
day_29_hour_6 = day_29_data[day_29_data['Hour'] == 6].head()
display(day_29_hour_6)

📊 ANÁLISIS DEL DATASET DE POTENCIA
==================================================
Total de registros: 520,800
Paneles únicos: 700
Período: 1 de enero - 31 de enero
Rango horario: 0h - 23h

🔋 ESTADÍSTICAS DE POTENCIA:
Potencia máxima: 12628.00 W
Potencia promedio: 907.89 W
Registros con potencia > 0: 207,900

⭐ MÁXIMA POTENCIA REGISTRADA:
Panel ID: 699.0
Área: 1.0 m²
Eficiencia: 22.0%
Día: 29.0, Hora: 6.0h
Irradiancia: 574.0 W/m²
Potencia: 12628.00 W

📅 EJEMPLO - DÍA 29 (día con máxima irradiancia):
Registros en el día 29: 16,800
Primeros 5 paneles en hora de máxima irradiancia (hora 6):

      Panel_ID  Apv(m2)  eta_stc(%)  Day  Hour  Gh(W/m2)  Power(W)
678        0.0     0.01        19.0   29     6       574    109.06
1422       1.0     0.01        19.5   29     6       574    111.93
2166       2.0     0.01        20.0   29     6       574    114.80
2910       3.0     0.01        20.5   29     6       574    117.67
3654       4.0     0.01        21.0   29     6       574    120.54